server:
  port: 8889
spring:
  application:
    name: microservice-provider-user1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true