server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    registerWithEureka: false  #自己不向eureka注册
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true